### ISSUE TITLE
Overture VDM-10 Tool Support: User Guide does not mention classpath

### ISSUE THREAD

**Issue by kgpierce** [overturetool/documentation#12]
Section 15.1.1 External Library Example gives example Java code but does not mention adding Overture jar to the class path, e.g.

javac -classpath "C:\Program Files\Overture\commandline\Overture-2.3.6.jar" sensor.java

**Comment by peterwvj** [comment]
I think this is mentioned in section "15.3.2 External Java Library". Would it suffice to add a forward reference to this section?

**Comment by kgpierce** [comment]
Ah yes. It applies to 15.1, 15.2 and 15.3, I think. Perhaps it could be moved to before these three?

**Comment by peterwvj** [comment]
That's probably a good idea. So you are suggesting that we move the part of section 15.3.2 that starts with "In order to use the VDM Types the Java implementation must have the Overture java library.." to before section 15.1? We can put it in a new section "15.0" called "Configuring the Java build path" or something like that. What do you think?

**Comment by kgpierce** [comment]
Yeah something like that would have helped me, since I obviously was too impatient to read ahead :-)

**Comment by nickbattle** [comment]
Ken, presumably you get a very particular class-not-found error? It might be good to mention that in the documentation too, as in "If you see this error... then you've forgotten to add the Overture.jar to the classpath"?

**Comment by kgpierce** [comment]
Yes that would be useful. For the example in 15.1, I get the following:

sensor.java:2: error: package org.overture.interpreter.runtime does not exist
import org.overture.interpreter.runtime.ValueException;
                                       ^
sensor.java:3: error: package org.overture.interpreter.values does not exist
import org.overture.interpreter.values.IntegerValue;
                                      ^
sensor.java:4: error: package org.overture.interpreter.values does not exist
import org.overture.interpreter.values.Value;
                                      ^
sensor.java:8: error: cannot find symbol
  public Value getValue(Value id) throws ValueException
                        ^
  symbol:   class Value
  location: class sensor
sensor.java:8: error: cannot find symbol
  public Value getValue(Value id) throws ValueException
         ^
  symbol:   class Value
  location: class sensor
sensor.java:8: error: cannot find symbol
  public Value getValue(Value id) throws ValueException
                                         ^
  symbol:   class ValueException
  location: class sensor
sensor.java:11: error: cannot find symbol
    return new IntegerValue(result);
               ^
  symbol:   class IntegerValue
  location: class sensor
7 errors

**Comment by peterwvj** [comment]
Okay that's done. Chapter 15 now includes a new section "15.1 Configuring the Java build path"

I did not add the error messages though. Feel free to tweak it all you want. I'm closing this issue for now.
