### ISSUE TITLE
Remote Control No/Unclear VDM_SL example

### ISSUE THREAD

**Issue by Kiguli** [overturetool/documentation#16]
Hi all, my first time every posting on something like this so bare with me please!

In chapter 16 of the Overture VDM-10 Tool Support: User Guide there is are a couple examples of using a Remote Control class but the examples do not actually work for VDM_SL. in particular 16.3 uses the interpreter.execute("new A().op(123)") which is not allowed in SL (also class/module A isn't given so it's a little hard to work out how it should be used effectively). Later in 16.5 there is the interpreter.create("w", "new World()") and interpreter.valueExecute("w.Run()") which also both can't be used by VDM_SL.

My suggested improvements would be:

1. Clarify which VDM (type?) the given examples work for and which they don't

2. Add a more generic section a bit like Appendix I (really useful for my project!) for the functions you can call in the remote controller and what they do.

3. A VDM_SL specific example. E.g.

@Override
	public void run(RemoteInterpreter interpreter) throws Exception {
		this.interpreter = interpreter;
		System.out.println("interpreter running");

               //sets the module MODULE_NAME as the default module to call methods from with the          interpreter
		this.interpreter.getInterpreter().setDefaultName("MODULE_NAME"); 

             //calls the method METHOD in the VDM module you are using with no input parameters
             interpreter.execute("METHOD()");

           //calls the method METHOD in the VDM module you are using with two input parameters
             interpreter.execute("METHOD( parameter1, parameter2)");

         //same as above but can concatenate strings
         interpreter.execute("METHOD( " + parameter[1] + " , " +  parameter[2] + ")");

        //get a value from the state or a type value
         interpreter.execute("state_variable.value"); -- e.g. current: <P1>|<P2>  in the state would be     
                                                                                  interpreter.execute("current");
}

The easy way of thinking about it is typing into the console in overture but omitting the print before whatever you call. (I didn't try what happens with just typing state as that doesn't have print before it in overture :O)

I would post more specific examples but don't want to get told I plagiarised myself when I submit my dissertation because I uploaded some code on here or something! I was using these methods to make a simple GUI where I can press buttons to run the code rather than type everything in console particularly records which I have in a list I can just select from rather than type out 7 different record parameters each time, phew!

Also shout out to Leo Freitas who helped me solve the issue I'd had on all this.

**Comment by nickbattle** [comment]
Thanks for reporting, Kiguli. I think the current examples focus on VDM++ and RT because there is a natural relationship between those dialects and a native Java (object oriented) library. But as you say, it is perfectly possible to use the native link with VDM-SL and there are some subtleties when doing so that ought to be brought out in the documentation.

Folks: I think we should review both the native library and remote control sections for VDM-SL support.
