### ISSUE TITLE
VCParser-masterSL has parse errors

### ISSUE THREAD

**Issue by peterwvj** [overturetool/documentation#18]
The VCParser-masterSL example currently has a few parse errors. As this example bundles with the tool this issue should be fixed before the next release. I'd appreciate if someone who knows the model well can help out.

Thanks!

**Comment by nickbattle** [comment]
@tomooda should be able to advise?

**Comment by tomooda** [comment]
I’ll work on this.

**Comment by nickbattle** [comment]
Are these really parser errors (syntax)? What did we change??

**Comment by peterwvj** [comment]
Thanks, Tomo. The spec is just malformed (it's not the tools).

**Comment by tomooda** [comment]
This (https://github.com/overturetool/documentation/commit/2e9bc1ef1446a63b9051849bcbd6e9508d9f972e) should resolve the syntax error.

**Comment by peterwvj** [comment]
Many thanks, Tomo! I'll make sure the tool gets updated accordingly.
