### ISSUE TITLE
References undefined in language manual PDF

### ISSUE THREAD

**Issue by mortenhaahr** [overturetool/documentation#25]
I just noticed that all the references are wrong in the available PDF version of the language [manual](https://github.com/overturetool/documentation/blob/editing/documentation/VDM10LangMan/VDM10_lang_man.pdf).

Furthermore, the font appears to be different from the rest of the documentation.

I tried rebuilding the PDF through the Makefile and the PDF is attached here
[VDM10_lang_man.pdf](https://github.com/overturetool/documentation/files/10098028/VDM10_lang_man.pdf). It seems to be a minor oversight in the latest commit.

**Comment by nickbattle** [comment]
Thanks for this Morten. @tomooda , are you able to fix this when you tweak the LRM?

**Comment by tomooda** [comment]
Yes, I'll be on it.

**Comment by tomooda** [comment]
it's now fixed. thank you for reporting this issue, @mortenhaahr :-)

**Comment by mortenhaahr** [comment]
You are welcome. And thank you for fixing it :-)
