### ISSUE TITLE
Update OvertureIDEUserGuide to remove proof status column

### ISSUE THREAD

**Issue by nickbattle** [overturetool/documentation#3]
The OvertureIDEUserGuide says that the POG view has a column with the proof status, which is ticked (discharged) if the PO matches one of a handful of trivial patterns. This was removed when the POG was updated to generate AST subtrees rather than strings - there is no such column in Overture 2.2.6.

**Comment by pglvdm** [comment]
This is fixed (among many other issues) in the manual for version 2.3.0
