### ISSUE TITLE
operator precedence of "reverse"

### ISSUE THREAD

**Issue by tomooda** [overturetool/documentation#7]
I don't find the "reverse" expression in the Operator Precedence section of LRM.
I suppose it should appear in the rhs of "sequence prefix operator" in C.3 and Table C.1.
I think precedence level of the "reverse" would be 6, which is the same precedence with the other sequence prefixes.
What precedence level is it implemented in Overture and VDMJ?

**Comment by nickbattle** [comment]
Hi Tomo,

Yes, "reverse" is implemented in the P6 group. Sounds like we need a small
update to the LRM then :)

**Comment by tomooda** [comment]
OK, this will be my weekend homework. :-)

**Comment by tomooda** [comment]
posted a pull request. https://github.com/overturetool/documentation/pull/8

**Comment by ldcouto** [comment]
GitHub's complaining about a conflict. I'll take a look at it.

**Comment by ldcouto** [comment]
Done. Just the pdf. Merge is not so good on binaries :)
